# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/janit/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-14324-Zephyrus-G16/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.cache/wt} [current_project]
set_property parent.project_path {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {c:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Add_Sub_Unit.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Comp.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Divider_8bit.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Even_Odd.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Instruction_Decoder.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/LUT_16_7.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Multiplier_4bit.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Nanoprocessor.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Program_Counter.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Program_ROM.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Register_Bank.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/Slow_Clk.vhd}
  {C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/new/MainProgram.vhd}
}
read_ip -quiet {{C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci}}

read_ip -quiet {{C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc}}]

read_ip -quiet {{C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/constrs_1/new/Basys3Labs.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/janit/OneDrive/Desktop/Vivado/Nanoprocessor - Additional Features/Nanoprocessor.srcs/constrs_1/new/Basys3Labs.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top MainProgram -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MainProgram.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MainProgram_utilization_synth.rpt -pb MainProgram_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
